plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.kotlin.compose) apply false
}

group = 'com.github.koros'
version = findProperty('VERSION_NAME') ?: System.getenv('RELEASE_VERSION') ?: System.getenv('VERSION') ?: '1.1.0-SNAPSHOT'
